### PR TITLE
feat: add cmake uninstall and lib install

### LINKED ISSUE #18: make install installs gtest
```
main@debian:~/Desktop/git/ddnet_protocol/build$ sudo make install
[sudo] password for chiller: 
[ 46%] Built target ddnet_protocol
[ 60%] Built target gtest
[ 73%] Built target gmock
[ 86%] Built target gmock_main
[100%] Built target gtest_main
Install the project...
-- Install configuration: ""
-- Up-to-date: /usr/local/include
-- Installing: /usr/local/include/gmock
-- Installing: /usr/local/include/gmock/gmock-more-actions.h
-- Installing: /usr/local/include/gmock/gmock-nice-strict.h
-- Installing: /usr/local/include/gmock/gmock-spec-builders.h
-- Installing: /usr/local/include/gmock/internal
-- Installing: /usr/local/include/gmock/internal/gmock-pp.h
-- Installing: /usr/local/include/gmock/internal/gmock-internal-utils.h
-- Installing: /usr/local/include/gmock/internal/gmock-port.h
-- Installing: /usr/local/include/gmock/internal/custom
-- Installing: /usr/local/include/gmock/internal/custom/README.md
-- Installing: /usr/local/include/gmock/internal/custom/gmock-generated-actions.h
-- Installing: /usr/local/include/gmock/internal/custom/gmock-port.h
-- Installing: /usr/local/include/gmock/internal/custom/gmock-matchers.h
-- Installing: /usr/local/include/gmock/gmock-cardinalities.h
-- Installing: /usr/local/include/gmock/gmock-function-mocker.h
-- Installing: /usr/local/include/gmock/gmock.h
-- Installing: /usr/local/include/gmock/gmock-more-matchers.h
-- Installing: /usr/local/include/gmock/gmock-actions.h
-- Installing: /usr/local/include/gmock/gmock-matchers.h
-- Installing: /usr/local/lib/libgmock.a
-- Installing: /usr/local/lib/libgmock_main.a
-- Installing: /usr/local/lib/pkgconfig/gmock.pc
-- Installing: /usr/local/lib/pkgconfig/gmock_main.pc
-- Installing: /usr/local/lib/cmake/GTest/GTestTargets.cmake
-- Installing: /usr/local/lib/cmake/GTest/GTestTargets-noconfig.cmake
-- Installing: /usr/local/lib/cmake/GTest/GTestConfigVersion.cmake
-- Installing: /usr/local/lib/cmake/GTest/GTestConfig.cmake
-- Up-to-date: /usr/local/include
-- Installing: /usr/local/include/gtest
-- Installing: /usr/local/include/gtest/gtest-param-test.h
-- Installing: /usr/local/include/gtest/gtest_prod.h
-- Installing: /usr/local/include/gtest/gtest-assertion-result.h
-- Installing: /usr/local/include/gtest/gtest-message.h
-- Installing: /usr/local/include/gtest/gtest.h
-- Installing: /usr/local/include/gtest/gtest-spi.h
-- Installing: /usr/local/include/gtest/gtest-typed-test.h
-- Installing: /usr/local/include/gtest/gtest-death-test.h
-- Installing: /usr/local/include/gtest/internal
-- Installing: /usr/local/include/gtest/internal/gtest-filepath.h
-- Installing: /usr/local/include/gtest/internal/gtest-type-util.h
-- Installing: /usr/local/include/gtest/internal/gtest-death-test-internal.h
-- Installing: /usr/local/include/gtest/internal/gtest-port-arch.h
-- Installing: /usr/local/include/gtest/internal/gtest-port.h
-- Installing: /usr/local/include/gtest/internal/custom
-- Installing: /usr/local/include/gtest/internal/custom/README.md
-- Installing: /usr/local/include/gtest/internal/custom/gtest.h
-- Installing: /usr/local/include/gtest/internal/custom/gtest-port.h
-- Installing: /usr/local/include/gtest/internal/custom/gtest-printers.h
-- Installing: /usr/local/include/gtest/internal/gtest-string.h
-- Installing: /usr/local/include/gtest/internal/gtest-internal.h
-- Installing: /usr/local/include/gtest/internal/gtest-param-util.h
-- Installing: /usr/local/include/gtest/gtest-matchers.h
-- Installing: /usr/local/include/gtest/gtest_pred_impl.h
-- Installing: /usr/local/include/gtest/gtest-printers.h
-- Installing: /usr/local/include/gtest/gtest-test-part.h
-- Installing: /usr/local/lib/libgtest.a
-- Installing: /usr/local/lib/libgtest_main.a
-- Installing: /usr/local/lib/pkgconfig/gtest.pc
-- Installing: /usr/local/lib/pkgconfig/gtest_main.pc
main@debian:~/Desktop/git/ddnet_protocol/build$ sudo make uninstall
make: *** No rule to make target 'uninstall'.  Stop.
```

I was hoping to install ddnet_protocol but got gtest instead. Also it can't be reverted.

### PR DESCRIPTION
**Pull request by ChillerDragon**
Closed #18

This will allow installing and uninstalling ddnet_protocol.
Also it stops gtest from installing it self.

### CODE REVIEW

**Comment by MilkeeyCat** [comment]
I'm not sure how I feel about generating `ddnet_protocol.h`, maybe it would be better to move header files to `include/ddnet_protocol` directory?

**Comment by ChillerDragon** [comment]
So that the user facing api becomes this?

```C
#include <ddnet_protocol/common.h>
```

Because this is bad 


```C
#include <common.h>
```

I actually tried that initially but then cmake only wanted to take one header so I rq. Justifying it with most libraries don provide you with 100 different headers for every little thing but they usually have one big one. Because then the user also has to know all the headers to include which can be annoying if you do not have a proper ide setup.

If you are sure about it I can give fighting cmake another try but keep in mind users code will look like this then


```C
#include <ddnet_protocol/common.h>
#include <ddnet_protocol/common.h>
#include <ddnet_protocol/common.h>
```

**Comment by ChillerDragon** [comment]
Okay I figured out how to add multiple headers. It takes a semicolon separated string. It now looks like this:

```
$ sudo make install
[100%] Built target ddnet_protocol
Install the project...
-- Install configuration: ""
-- Up-to-date: /usr/local/lib/libddnet_protocol.a
-- Up-to-date: /usr/local/include/ddnet_protocol/common.h
-- Up-to-date: /usr/local/include/ddnet_protocol/errors.h
-- Up-to-date: /usr/local/include/ddnet_protocol/token.h
-- Up-to-date: /usr/local/include/ddnet_protocol/chunk.h
-- Up-to-date: /usr/local/include/ddnet_protocol/packet.h
-- Up-to-date: /usr/local/include/ddnet_protocol/packer.h
-- Up-to-date: /usr/local/include/ddnet_protocol/huffman.h
```

There is a new include/ directory for only the public headers. This is apparently good style according to stackoverflow and also [SDL](https://github.com/libsdl-org/SDL/tree/main/include) does it like that.
This gives us full control to also optionally exclude private headers in the future. But for now everything is exposed.

But it comes with no manual maintenance overhead. The new script ``./scripts/genarate_public_includes.sh`` copies the code files over and even adds them automatically to the CMakeListst.txt. If you forget to run in the CI will remind you.

**Comment by ChillerDragon** [comment]
Hm I can no longer build the example with the multiple headers let me check

```
$ nm /usr/local/lib/libddnet_protocol.a

chunk.c.o:
0000000000000000 T decode_chunk_header

control_packet.c.o:
0000000000000000 T decode_control
                 U malloc
                 U read_token
                 U strlen
                 U strncpy
                 U TOKEN_MAGIC

huffman.c.o:
0000000000000000 t bubble_sort_nodes
00000000000001b6 t construct_tree
0000000000002040 b decode_luts
0000000000000000 r FREQUENCY_TABLE
0000000000000559 T huffman_compress
0000000000000744 T huffman_decompress
0000000000000412 t huffman_init
0000000000000000 B huffman_initialized
                 U memset
0000000000000020 b nodes
0000000000004048 b num_nodes
00000000000000f6 t setbits_r
0000000000004040 b start_node

packer.c.o:
000000000000003f T unpacker_get_int
00000000000001c9 T unpacker_get_raw
0000000000000000 T unpacker_new

packet.c.o:
0000000000000087 T decode
                 U decode_control
0000000000000000 T decode_packet_header

token.c.o:
0000000000000000 T read_token
0000000000000000 R TOKEN_MAGIC
$ g++ ./examples/huffman.c -o huffman -lddnet_protocol
/usr/bin/ld: /tmp/ccKie0u5.o: in function `main':
huffman.c:(.text+0x3b): undefined reference to `huffman_decompress(unsigned char const*, unsigned long, unsigned char*, unsigned long)'
collect2: error: ld returned 1 exit status
```

**Comment by ChillerDragon** [comment]
Okay I am quite happy with the final result :rocket: :tada: 
This is the first C library I worked on and it feels properly setup and usable.
Now we can start extending the examples/ folder to get users quick started and the CI can catch if we break the users code!

**Comment by ChillerDragon** [comment]
Okay now the example code in the README.md is also checked in the CI using [lintdown.sh](https://github.com/ChillerDragon/lintdown.sh) this makes sure never get trolled by an outdated example in the readme.

**Comment by MilkeeyCat** [comment]
Thanks you so much!

**Comment by MilkeeyCat** [comment]
It just copies header files from `src` in `include/ddnet_protocol`, but my idea was to remove header files from `src` and move them in `include/ddnet_protocol` and use use header including magic so you still could include them as `#include "common.h"`, do you think it's a bad ideas?

**Comment by ChillerDragon** [comment]
I think I read somewhere it is good style to keep them separate. I would go with that for now. For me it also feels right to have a clear separation between public and private headers. Then we can always decide to alter the generation pipeline from doing a copy to something more advanced that filters out private headers or internal variables.

But I am not fully educated on the matter. Could also be fancy to do a ``#include <ddnet_protocol/common.h>`` from the ``token.cpp`` file instead of just ``#include "common.h"``

Whats your motivation for not having it twice? Reduced repo size? Reduced code search hits (could be solved by tweaking your search tool)?

**Comment by MilkeeyCat** [comment]
I just don't like 2 same files in the repo xd

**Comment by ChillerDragon** [comment]
No particular reason?

**Comment by MilkeeyCat** [comment]
I thought we can reuse reuse them so there's no need to copy them in `include` dir

**Comment by ChillerDragon** [comment]
I have no super hard feelings on it but I prefer how it is currently. After having this cmake maintainer guy yap about the importance of limiting what you expose in a library https://www.youtube.com/watch?v=m0DwB4OvDXk. So the user does not use the internal api without you intending it I like the idea of dedicated headers.

Also while developing the library i like doing ``touch src/foo.{c,h}`` instead of searching the header file in a different directory than the source file.

We could also not track the include/ directory as long as it is a unmodified copy anyways it could also be generated on demand (install and package).

**Comment by MilkeeyCat** [comment]
Oh way, I wanted to say that only public header files should be moved into `include` dir, not all header files. But it's still probably not a good way, so we will leave it like this.

**Comment by MilkeeyCat** [comment]
Ok, I actually think simply moving public headers into `include` dir would be better xd. There's only one way to know which way it better, it will be decided with a game of rock paper scissors https://www.rpsgame.org/room?id=lppav

**Comment by ChillerDragon** [comment]
rigged

image

**Comment by ChillerDragon** [comment]
Sure fine by me. But you do it :p

**Comment by MilkeeyCat** [comment]
Ye

**Pull request merged**
