### PR TITLE
refcators rename control file and move token field

### LINKED ISSUE #50: control packet or packet control?
The filename is `control_packet.h` and the struct name is ``PacketControl``

Is this intentional? if yes we can close the issue. If not I think having some consistency would be nice.

### PR DESCRIPTION
**Pull request by ChillerDragon**
Closed #50

### CODE REVIEW

**Comment by MilkeeyCat** [comment]
What does the `Session` struct do?

**Comment by ChillerDragon** [comment]
Nothing yet. But every user that wants a working connection will have to create something like this.
So if you build a client you initialize a session struct to store your own security token and the servers token and keep track of all the vital messages being sent. It is used to drop packets with wrong security tokens and ask for resends if sequence numbers got lost.

In [twnet_parser](https://gitlab.com/teeworlds-network/twnet_parser) I said that the connection state machine is specifically out of scope. I am not sure what your plan is for ddnet_protocol. If it should exclusively do parsing of packets without any further state and session management is up to the user or if you want to offer a simple framework for client and servers. Either way I think providing this session struct is nice.

**Comment by MilkeeyCat** [comment]
I think that session struct is out of scope for this library. The lib simply parses/encodes packets, not less, not more. The user of the lib can build whatever he wants around the library.

**Comment by ChillerDragon** [comment]
> I think that session struct is out of scope for this library. The lib simply parses/encodes packets, not less, not more. The user of the lib can build whatever he wants around the library.

Sure okay. Totally fine by me. The reason it happend in the first place is that I wanted to mention MAX_SEQUENCE in the chunk documentation and did not know where to define that constant. Also I was planning to add the [IsSeqInBackroom](https://github.com/ddnet/ddnet/blob/faf0af5ec476d7effba02f41a62c2cba3cb1e3d7/src/engine/shared/network.cpp#L381-L398) function to the library which would also belong into the session header. That is just such an annoying function to implement and anyone who wants to do some serious networking will need to implement it. So while at it I already drafted the session struct so it can be used later and also to fully document the sequence numbers.

I kicked it out no problemo. And moved this part into chunk.h

```C
// The sequence and acknowledge number can never
// be higher than 1024
#define MAX_SEQUENCE 1 << 10
```

**Comment by MilkeeyCat** [comment]
Thanks!

**Pull request merged**
