### PR TITLE
feat: cl start info message

### PR DESCRIPTION
**Pull request by MilkeeyCat**

### CODE REVIEW

**Comment by ChillerDragon** [comment]
Looks good. But the more messages we add the harder refactoring will become. Are we happy with this layout? You mentioned that you want the struct to be responsible for packing the system flag and message id. It is not doing that right now.

**Comment by MilkeeyCat** [comment]
I'm not sure what you mean

**Comment by ChillerDragon** [comment]
I am referring to [this comment](https://github.com/MilkeeyCat/ddnet_protocol/pull/57#issuecomment-2547669633). Every vital message has 3 bytes of chunk header followed by 1-2 bytes message id plus system flag and then the payload. This message id and system flag information is currently not represented in the struct. This pr is about decoding not encoding so the message id was already unpacked elsewhere.

The pr can be merged as is right now all good. I am just saying before we add any more messages we should probably look at packing messages.

**Comment by MilkeeyCat** [comment]
Do you think it's better to store that data in the struct or have a function which will take `ChunkKind` and return message id and `MessageKind`?

**Pull request merged**
