### PR TITLE
feat: add fix_style.py from ddnet repo

### PR DESCRIPTION
**Pull request by ChillerDragon**

### CODE REVIEW

**Comment by MilkeeyCat** [comment]
Tbh I don't think I need dis pyson script, I think a bash file with
```sh
find . -path './build' -prune -o \( -name '*.h' -o -name '*.c' \) -exec clang-format -style=file -i {} \;
```
is enough

**Comment by ChillerDragon** [comment]
Yea sounds good

**Comment by ChillerDragon** [comment]
Have to think about this can be used in the CI then.

**Comment by MilkeeyCat** [comment]
Sorry, I forgot that there're also `.cc` test files, can you pls add them and I will merge the pr

**Comment by MilkeeyCat** [comment]
Thanks!

**Pull request merged**
