### PR TITLE
ci: run fix_style.py in ci

### PR DESCRIPTION
**Pull request by ChillerDragon**
Depends on #1

### CODE REVIEW

**Comment by ChillerDragon** [comment]
Now since #1 is no longer pyson it would need a rewrite to something like

```
#!/bin/bash

clang_arg="${1:--i}"

while read -r src_file
do
	clang-format -Werror "$clang_arg" "$src_file" || exit 1
done < <(find ./src \( -name '*.h' -o -name '*.c' \))
```

to work in the CI

**Comment by ChillerDragon** [comment]
Yes thats it.

**Comment by MilkeeyCat** [comment]
Ig to make it work you have to slap `--dry-run`

**Comment by MilkeeyCat** [comment]
Also, choose between js, ruby or pyson(lang for generating game messages) xd

**Comment by ChillerDragon** [comment]
> Ig to make it work you have to slap `--dry-run`

Yes

**Comment by ChillerDragon** [comment]
Should work now

**Comment by MilkeeyCat** [comment]
Thanks!

**Pull request merged**
